### ISSUE TITLE
Trying to boot 6.8.7 (amd64) on Debian 12 (N100, 16GB RAM)

### ISSUE THREAD

**Issue by vanfanel** [CachyOS/linux-cachyos-deb#2]
Hi there,

I ran this script today on my Intel N100 computer and it built the 6.8.7 kernel successfully.
After building the kernel, I installed both the resulting kernel and headers deb packages:
```
dpkg -i linux-6.8.7/custom-kernel-6.8.7-6.8.7-1.deb
dpkg -i linux-6.8.7/custom-kernel-headers-6.8.7-6.8.7-1.deb

```
Then created an initramfs image for the 6.7 kernel:
`update-initramfs -c -k 6.8.7`
Then ran `update-grub` so GRUB could find the new kernel, then on the GRUB boot menu, I entered `Advanced options` and selected the 6.8.7 kernel.
But all I get when booting the kernel is:

```
Loading Linux 6.8.7...
Loading initial ramdisk...
error: out of memory

Press any key to continue...
```

Before that, I tried to boot the 6.8.7 kernel without creating it's initramfs, and it wouldn't stall in `Loading Linux 6.8.7...`, so my guess is that I did something wrong when creating the initramfs for the kernel. But this is just a guess. Any ideas, please?

**Comment by lseman** [comment]
Hum, maybe you can generate the initramfs stripping all symbols in the modules
_install, like:

make INSTALL_MOD_STRIP=1 modules_install

Per default, the script uses the .config from cachyos, which maybe is too much for your system (I don't know why, since 16GB should be enough RAM). Maybe you can create a "thin" kernel with modprobed-db. See, for instance, https://wiki.archlinux.org/title/Modprobed-db

**Comment by vanfanel** [comment]
@lseman Hey thanks! You put me on the right track: after installing the modules manually with: 

`make INSTALL_MOD_STRIP=1 modules_install`

and then installing the kernel and generating a new initramfs for it with:

`make install`

...I am now on Cachyos 6.8.7 Kernel on Debian 12!

The key here was to install things manually instead of installing the .deb packages, it seems.

Oh, and many many thanks for the modprobed-db tip, really: it's something I had been doing for many years "by hand", but that is much better!

**Comment by osevan** [comment]
Is this fixed inside bash script too?
